security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_forward: false
                use_referer: true
            logout:       true
            anonymous:    true
            remember_me:
                key: "%secret%"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%isometriks_symedit.admin_dir%, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SUPER_EXTEND
            - ROLE_ADMIN_BLOG
            - ROLE_ADMIN_WIDGET
            - ROLE_ADMIN_IMAGE
            - ROLE_ADMIN_SETTING
            - ROLE_ADMIN_PAGE
            - ROLE_ADMIN_USER
            - ROLE_ADMIN_WEBMASTER
            - ROLE_ADMIN_EDITABLE
            - ROLE_ADMIN_STYLIZER