language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.6
        - php: 7.0
    allowed_failures:
        - php: 7.0

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer self-update
    - composer install --prefer-dist --no-scripts --no-interaction
    - composer run-script travis-build --no-interaction

before_script:
    - php bin/console symedit:install --force --env=test -v

script:
    - phpunit
    - bin/behat