imports:
    - { resource: parameters.yml }
    - { resource: @SymEditBundle/Resources/config/app/main.yml }

framework:
    esi:                        ~
    translator:
        fallback:               %locale%
    secret:                     %secret%
    router:
        resource:               "%kernel.root_dir%/config/routing.yml"
        strict_requirements:    %kernel.debug%
    form:                       true
    csrf_protection:            true
    validation:
        enable_annotations:     false
    templating:
        engines:                ['twig']
    default_locale:             %locale%
    session:                    ~
    fragments:                  ~
    http_method_override:       true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ SymEditBundle ]
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            compress: true
        uglifycss:
            bin: /usr/bin/uglifycss
            ugly_comments: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
#    spool:      { type: memory }
    transport:  %mailer_transport%
    username:   %mailer_user%
    password:   %mailer_password%
    port:       %mailer_port%
    host:       %mailer_host%
