imports:
    - { resource: config.yml }
    - { resource: security.yml }

framework:
    test: ~
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
            storage_id: session.storage.mock_file

assetic:
    use_controller: true

web_profiler:
    toolbar: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        dbname:   %database_name%_test
