SymEdit\Bundle\FormBuilderBundle\Model\Form:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"

SymEdit\Bundle\FormBuilderBundle\Model\FormElement:
    properties:
        name:
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"

