SymEdit\Bundle\CoreBundle\Model\Category:
    type: entity
    table: category
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        seo:
            type: json_array
            nullable: true
    manyToOne:
        parent:
            targetEntity: SymEdit\Bundle\CoreBundle\Model\CategoryInterface
            inversedBy: children
            joinColumns:
                parent:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    oneToMany:
        children:
            targetEntity: SymEdit\Bundle\CoreBundle\Model\CategoryInterface
            cascade:
                - remove
                - persist
            mappedBy: parent
    manyToMany:
        posts:
            targetEntity: SymEdit\Bundle\CoreBundle\Model\PostInterface
            mappedBy: categories
            orderBy:
                createdAt: DESC
    lifecycleCallbacks:
        prePersist:
            - fixSlug
