imports:
    - { resource: "@SymEditBundle/Resources/config/app/symedit.yml" }

# Gaufrette Configuration
knp_gaufrette:
    adapters:
        symedit_image:
            local:
                directory: %kernel.root_dir%/../web/media/image
                create: true
        symedit_file:
            local:
                directory: %kernel.root_dir%/../web/media/file
                create: true
    filesystems:
        symedit_image:
            adapter: symedit_image
        symedit_file:
            adapter: symedit_file

# Liip Imagine Configuration
liip_imagine:
    driver: imagick
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/media/image
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
    cache: default
    filter_sets:
        gallery_thumbnail:
            filters:
                upscale: { min: [350, 200] }
                thumbnail: { size: [350, 200], mode: outbound }
                background: { size: [350, 200], position: center, color: '#ffffff' }
        gallery:
            filters:
                thumbnail: { size: [800, 400], mode: inset }
        blog_thumbnail:
            filters:
                relative_resize: { widen: 850 }
                thumbnail: { size: [850, 200], mode: outbound }
        blog:
            filters:
                relative_resize: { widen: 850 }
                thumbnail: { size: [850, 400], mode: outbound }
        symedit_64x64:
            filters:
                upscale: { min: [64, 64] }
                thumbnail: { size: [64, 64], mode: outbound }
        symedit_96x96:
            filters:
                upscale: { min: [96, 96] }
                thumbnail: { size: [96, 96], mode: outbound }

# User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    from_email:
        address: notused@overriden.com
        sender_name: overridden
    service:
        mailer: symedit_user.mailer
    registration:
        confirmation:
            enabled: true
            template: "@SymEdit/Email/confirm.html.twig"
    resetting:
        email:
            template: "@SymEdit/Email/resetting.html.twig"

# Rest Configuration
fos_rest:
    view:
        formats:
            json: true
            xml: true
            rss: true
        templating_formats:
            rss: true
            html: true
        mime_types:
            rss: 'application/rss+xml'
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

# MopaBootstrap Configuration
mopa_bootstrap:
    menu: ~
    icons:
        icon_set: fontawesome4
    form:
        allow_legacy: true
        show_legend: false
        render_required_asterisk: true
        render_optional_text: false
        checkbox_label: label

# Form Spam Configuration
isometriks_spam:
    honeypot:
        field: email_address
        use_class: true

# CMF Routing
cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            symedit.dynamic_router: 100
    dynamic:
        route_provider_service_id: symedit.routing.route_provider

# JMS Serializer Configuration
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@SymEditUserBundle/Resources/config/serializer/fos"

# Pagination Configuration
white_october_pagerfanta:
    default_view: twitter_bootstrap3

# Stof Doctrine Extension
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true
            tree: true
            loggable: true
            blameable: true

# Doctrine Cache
doctrine_cache:
    providers:
        symedit_analytics:
            type: file_system

# Isometriks Json LD
isometriks_json_ld_dumper:
    static:
        logo:
            mapping:
                "@context": http://schema.org/
                "@type": ImageObject
                url: "expr:setting('company.logo', false) ? absolute_url(setting('company.logo').getWebPath()) : ''"

        company:
            always_include: true
            mapping:
                "@context": http://schema.org/
                "@type": Organization
                address:
                    "@type": PostalAddress
                    streetAddress: "expr:setting('company.address', '')"
                name: "expr:setting('company.name')"
                logo: $static.logo
                image: $static.logo
                url: "expr:absolute_url('/')"
                contactPoint:
                    "@type": ContactPoint
                    telephone: "expr:'+1-' ~ setting('company.phone', '')"
                    email: "expr:setting('company.email', '')"
                    contactType: customer service

    entity:
        %symedit.model.post.class%:
            mapping:
                "@context": http://schema.org/
                "@type": NewsArticle
                headline: $resource.title
                publisher: $static.company
                image: $resource.image
                datePublished: $resource.publishedAt
                dateModified: $resource.updatedAt
                author: $resource.author.profile.fullName

        %symedit.model.event.class%:
            mapping:
                "@context": http://schema.org/
                "@type": Event
                name: $resource.title
                url: $resource.url
                description: $resource.description
                startDate: $resource.eventStart
                endDate: $resource.eventEnd
                image: $resource.image
                location:
                    "@type": PostalAddress
                    streetAddress: $resource.address


        %symedit.model.image.class%:
            mapping:
                "@context": http://schema.org/
                "@type": ImageObject
                url: "expr:context ? absolute_url(context.getWebPath()) : null"
                width: "expr:context.getMetadata()['width'] ~ 'px'"
                height: "expr:context.getMetadata()['height'] ~ 'px'"
